### PR TITLE
Added mention plugin package from ckeditor repo

### PR DESCRIPTION
**Pull request by braydend**
Adds the mentions plugin locally so we can alter the source as we need

### CODE REVIEW

**Review by jack-estimateone — APPROVED** [review]

**Comment by BBlackwo** [comment]
Rather than pulling in the entire source into this repo, would it be better to:
1) Fork the project into it's own repo in E1 or
2) Use [patch-package](https://www.npmjs.com/package/patch-package) (if the changes are small enough).

That way as the plugins gets updated it might be easier to pull the updates into our modified plugin?

**Comment by braydend** [comment]
> Rather than pulling in the entire source into this repo, would it be better to:
> 
>     1. Fork the project into it's own repo in E1 or
> 
>     2. Use [patch-package](https://www.npmjs.com/package/patch-package) (if the changes are small enough).
> 
> 
> That way as the plugins gets updated it might be easier to pull the updates into our modified plugin? Otherwise our copy might become very out of date and not be compatible with future CKEditor versions?

Good call, I'll look into forking the plugin :)

**Comment by jack-estimateone** [comment]
> Rather than pulling in the entire source into this repo, would it be better to:
> 
> 1. Fork the project into it's own repo in E1 or
> 2. Use [patch-package](https://www.npmjs.com/package/patch-package) (if the changes are small enough).
> 
> That way as the plugins gets updated it might be easier to pull the updates into our modified plugin? Otherwise our copy might become very out of date and not be compatible with future CKEditor versions?

good advice from CKEditor expert! 👍

**Comment by braydend** [comment]
Closing in favour of: https://github.com/estimateone/forsite-ckeditor-mentions

**Pull request closed without merging**
